CREATE TABLE IF NOT EXISTS "MPA_RATING"
(
    "MPA_RATING_ID"   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY  ,
    "MPA_RATING_NAME" varchar not null
);

CREATE TABLE IF NOT EXISTS "GENRE"
(
    "GENRE_ID"   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GENRE_NAME" varchar not null
);

CREATE TABLE IF NOT EXISTS "FILMS"
(
    "FILM_ID"       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NAME"          varchar      not null,
    "DESCRIPTION"   varchar(200) not null,
    "RELEASE_DATE"  date         not null,
    "DURATION"      int          not null,
    "MPA_RATING_ID" int references MPA_RATING (MPA_RATING_ID)
);

CREATE TABLE IF NOT EXISTS "USERS"
(
    "USER_ID"  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NAME"     varchar,
    "LOGIN"    varchar not null,
    "EMAIL"    varchar not null,
    "BIRTHDAY" date    not null
);

CREATE TABLE IF NOT EXISTS "LIKES"
(
    "LIKE_ID" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FILM_ID" int references FILMS (FILM_ID) not null,
    "USER_ID" int references USERS (USER_ID) not null
);

CREATE TABLE IF NOT EXISTS "FRIENDSHIP"
(
    "ID"        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FRIEND_ID" int references USERS (USER_ID) not null,
    "USER_ID"   int references USERS (USER_ID) not null
);

CREATE TABLE IF NOT EXISTS "FILM_GENRE"
(
    ID       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FILM_ID  int REFERENCES FILMS (FILM_ID),
    GENRE_ID int references GENRE (GENRE_ID)
)